### ISSUE TITLE
Add remaining date data to the API

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1385]
**Stories:**
- [1](https://18f.storiesonboard.com/m/fec/!card/IovpMAadH296NDnT3Laojg) So that filers know when to file their reports, show all reporting deadlines as a calendar.
- [2](https://18f.storiesonboard.com/m/fec/!card/JqiSFWrlBptCOjnT3Laojg): So that filers various election activity periods, show them on a calendar, filterable by deadline-type and state.
- [3](https://18f.storiesonboard.com/m/fec/!card/5X1JTYVxlgg6XznT3Laojg): So that the public can follow the commission's decision-making activity, show dates for meetings, AOs, and other activities on a calendar.

**Goal:** We need to get all remaining data from the FEC for the calendar, including:
- [ ] State values for the reporting deadlines
- [ ] IE, EC and pre- and post-election periods (and state values)
- [ ] Dates for events, meetings, AOs, etc (non-reporting dates)*

This data should come from the new tables, not the data warehouse. Once we get it, put it in the API.

**Tasks:**
- [ ] Get data
- [ ] Put it into API

* @LindsayYoung assigning this to you, but let me know if I got anything wrong in the issue description. Not 100% sure I captured everything right.
