### ISSUE TITLE
Document sources used for each datatable page

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1501]
**[Story](https://18f.storiesonboard.com/m/fec/!card/2vPsOOo-aFMyvznV1V5DsQ)**: So that users and the team can have confidence in the data included in each browse table, provide documentation in the app that explains what is included in each table.

**Tasks:**
- [ ] Create a place for documenting where each new datatable draws its data from
- [ ] 18F fill out based on current understanding
- [ ] Verify with FEC

**Comment by noahmanger** [comment]
There's various components to documenting this data for users and our team:
- Which data is included on each browse page?
- How does each column in the table and field in the panel relate to the underlying data?
- How does each filter relate to the underlying data? 

Because this need is shared by both our team and our users, we need to find a way to not just document the answers to each of these questions, but we need to expose them to the public somehow. 

I know that there's already been a lot of work put into documenting these very things on the API, so I'm hoping we can leverage that. And if we can leverage it in automated ways, then all the better.

This task is just to build the documentation, and then there will be separate tasks for figuring out how to expose it. I think ideally that would be through pages on the actual website, but maybe it's simply by directing people to a place in our repo. 

So if the end goal is to share this documentation between our team and the public, I'd love thoughts on the best place for this to live. Is it simply a documentation markdown file that we maintain and that gets pulled into the live site somehow? Is on the wiki? Is there a way to share this between the API and the web app?

**Comment by LindsayYoung** [comment]
Yea, for the more complicated stuff, I would like to use https://api.open.fec.gov/swagger/ as much as possible to explain the data once. (Still have a pr out to add more there.)

**Comment by noahmanger** [comment]
Based on our discussion yesterday, we're going to continue to improve our swagger documentation, using GitHub issues to detail new features. Once a feature is implemented, we'll update the swagger documentation accordingly. I'm going to close this.
