### ISSUE TITLE
Review data needed for individual contributions + operating expenditures tables

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1567]
Before we begin development on the individual contributions and operating expenditures table pages, we need to identify what (if any) new data we need. 

**Tasks:**
- [x] Go through master column spreadsheet and identify if each field is already represented in the API

If all fields are included, we can move into implementation.

**Comment by noahmanger** [comment]
Here's the filters and fields that I see we're missing:

**Individual contributions and receipts from committees:**
- [ ] *Recipient* committee type & designation
- [ ] *Contributing* committee type & designation
- [ ] Recipient committee associated candidate (i.e. authorized committee of a candidate)
- [ ] Transaction date (we just have date reported to FEC now, right?)

**Operating expenditures**
- [ ] Spending committee's affiliated candidate
- [ ] Spending committee type & designation
- [ ] Transaction date

And then for distinguishing Operating Expenditures from overall disbursements, are those already easy enough to identify by transaction codes or do we need to build that as well?

**Comment by LindsayYoung** [comment]
We have transaction dates- that is what we do the filtering on.

**Comment by noahmanger** [comment]
Oh, thanks. In that case we need filing dates. We want both. Do we have that as well? I didn't see it in the API docs.

**Comment by noahmanger** [comment]
Update from the meeting: New filters should come after fixing all performance issues, but in the mean time can make these pages without the new filters.

**Comment by noahmanger** [comment]
Ok, made new issues for the API tasks as well as for making the new pages using the existing filters. So closing this.
