### ISSUE TITLE
Information Architecture Usability Results

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/openFEC#1809]
# Tests overview

We've completed three unmoderated treejack tests:
1. An initial draft information architecture, built by our team based on our research (tasks 1–3 below).
   - Ran June 10–15
   - 58 people completed
2. A revised information architecture based on our findings in the first round of testing (tasks 4–7 below).
   - Ran June 22–July 7
   - 59 people completed
3. A test of the existing FEC.gov site structure to get baseline metrics for all tasks (1–7).
   - Ran July 7–12
   - 87 people completed

We will continue to test and iterate as we move forward. We're also keeping an eye on incorrect responses that had only a single user select them. Single responses are worth monitoring but not yet a trend.
# Task 1:
### You want to learn more about what types of reports candidates need to file and when. Where would you go?

![screen shot 2016-06-16 at 10 25 47 am](https://cloud.githubusercontent.com/assets/10552702/16120939/508af97e-33af-11e6-94fe-e1578bd7a1ef.png)

| Existing architecture | New architecture |
| --- | --- |
| Success: **65%** | Success: **63%** |
| Directness: **71%** | Directness: **72%** |
| Time taken: **16 seconds** | Time taken: **28 seconds** |

This result is from our first test, where the most common incorrect paths were through **Campaign finance data** and **Education and training**. In our second iteration, we removed **Education and training** and added a **Library** of publications instead. We've also added more clear paths on the beta site between the **Campaign finance data** section and the **Registration and reporting** section. 
# Task 2:
### You know the FEC sometimes resolves disputes using a program  called the Alternative Dispute Program. Where would you go to find more information about this?

![screen shot 2016-06-16 at 10 25 52 am](https://cloud.githubusercontent.com/assets/10552702/16120947/546ef7ac-33af-11e6-9daf-023b703577d1.png)

| Existing architecture | New architecture |
| --- | --- |
| Success: **64%** | Success: **82%** |
| Directness: **48%** | Directness: **68%** |
| Time taken: **28 seconds** | Time taken: **18 seconds** |
- We see clear signals here for keeping **Enforcement matters** as both a top-level item and nested within **Legal resources**
# Task 3:
### You’d like to attend a regional conference hosted by the FEC. Where would you go to find more information about regional conferences?

![screen shot 2016-06-16 at 10 25 57 am](https://cloud.githubusercontent.com/assets/10552702/16120948/566626b6-33af-11e6-97f0-8a01d4419256.png)

| Existing architecture | New architecture |
| --- | --- |
| Success: **5%** | Success: **93%** |
| Directness: **51%** | Directness: **82%** |
| Time taken: **23 seconds** | Time taken: **14 seconds** |
# Task 4:
### You'd like to find out what the maximum amount one person can donate to a candidate . Where would you go to find that?

<img width="1129" alt="screen shot 2016-07-13 at 5 06 06 pm" src="https://cloud.githubusercontent.com/assets/10552702/16823885/397ad81c-491c-11e6-8d44-926dab460756.png">

| Existing architecture | New architecture |
| --- | --- |
| Success: **51%** | Success: **64%** |
| Directness: **50%** | Directness: **25%** |
| Time taken: **28 seconds** | Time taken: **35 seconds** |

This one still needs IA work. The 64% success rate is an improvement over the existing site, but it's not where we'd like it to be. We also had lower directness and more time taken. This indicates to us that either we don't have the right spot for this piece of content or we don't have the right language.
# Task 5:
### Where would you go to learn how to report a possible FEC violation?

<img width="1140" alt="screen shot 2016-07-13 at 5 06 15 pm" src="https://cloud.githubusercontent.com/assets/10552702/16823921/77092b66-491c-11e6-9695-dac05f7af57f.png">

| Existing architecture | New architecture |
| --- | --- |
| Success: **27%** | Success: **79%** |
| Directness: **56%** | Directness: **51%** |
| Time taken: **25 seconds** | Time taken: **22 seconds** |
# Task 6:
### Where would you go to sign up for the "FEC Record," the FEC's newsletter?

<img width="1139" alt="screen shot 2016-07-13 at 5 06 21 pm" src="https://cloud.githubusercontent.com/assets/10552702/16823895/4b1933d4-491c-11e6-86e9-46327411b544.png">

| Existing architecture | New architecture |
| --- | --- |
| Success: **1%** | Success: **74%** |
| Directness: **66%** | Directness: **56%** |
| Time taken: **13 seconds** | Time taken: **23 seconds** |
# Task 7:
### Where would you go to find information about how to register as a party committee?

<img width="1136" alt="screen shot 2016-07-13 at 5 06 27 pm" src="https://cloud.githubusercontent.com/assets/10552702/16823893/42b6238c-491c-11e6-830c-b71b356af0c2.png">

| Existing architecture | New architecture |
| --- | --- |
| Success: **51%** | Success: **64%** |
| Directness: **60%** | Directness: **87%** |
| Time taken: **28 seconds** | Time taken: **18 seconds** |
- While the success rate is lower than we'd like on this one, but we don't think it's due to the hierarchy:
  - The directness is very high. 
  - Failures in this task were almost entirely people clicking into the wrong _type_ of registrant, rather than going to the wrong section of the website. People knew where to go at a high level (`Registration and reporting`), but they didn't seem to understand the nuances between things like `party committee` and `candidate committee`. 
- The failures in the FEC.gov section are all over the map. Such a broad distribution of paths indicates there aren't good signals at the high level, and we believe the top-level hierarchy is most important, because that gets users closer to the right answer. 
# To dos:

These are some possible fixes we identified that don't affect the proposed hierarchy but could make it easier for users to navigate.
🔧 Create prominent pathways from data to legal content
🔧 Add a _subscription_ section to Contact us. A number of people looked to this page for subscribing options, and adding this feature would redirect folks and possibly decrease call volume to FEC.
# Hierarchy

Here's a PDF document of our proposed site structure. It's important to note that this isn't a proposal for a top-level navigation menu; for example, we wouldn't include things like "Reports about the FEC" in a top site menu. We'll design solutions with Jen and Noah and Jeremy, but some things might exist  as footer items, others as homepage body content, etc.

[Proposed IA.pdf](https://github.com/18F/openFEC/files/364672/Proposed.IA.pdf)
# Next steps
- [x] Present to18F team and get feedback. Refine.
- [x] Present to FEC team to get their input and support. 
- Implementation (huuuuugggee, with so many steps):
  - [x] IA design interface questions (So many questions: What will this IA look like? How will users navigate? Is it a menu or something else?)
  - [x] Identify all website content types (Issue: https://github.com/18F/fec-cms/issues/392)
  - [x] Prioritize pages for migration and cross-linking with FEC team (Decided: Library) (Issue: https://github.com/18F/fec-cms/issues/404)
  - [x] Improve Wagtail and train FEC to use it (Issue: https://github.com/18F/fec-cms/issues/403)

**Comment by emileighoutlaw** [comment]
@AmyKort — I'm tagging you in to take a look at these results. It's a lot to take in, so let me know what questions you have. 

Let's video chat strategy and next steps this week. :)

**Comment by AmyKort** [comment]
Awesome! I'll take a look!
