### ISSUE TITLE
Add plain language summaries to AOs

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2153]
So that a users can quickly understand what an AO is about, add the approved, plain-language summary that is already published in the FEC Record to each AO's canonical page.

---

This story is to capture the AO summaries from FEC Record articles, add them to the API response, and then implement them on the front-end. 

~The one unknown here is what the exact rules for this content are and what the best way to get it is. I'm not sure if it exists in a more structured form than what's on the website currently.~

**Update from [here](https://github.com/18F/openFEC/issues/2155#issuecomment-272547012):** Because Records before ~2009 or so are only available as PDFs, FEC is offering to help collect these descriptions into an easier to use format.

**Sub-tasks**
- [x] Figure out what parts need
- [ ] @amypike discuss with info division to see how long it takes
- [x] Figure out the best mechanism for getting the content

---

## Update 2
While doing some technical scoping, I made the changes necessary to support this on the CMS ready to review here: https://github.com/18F/fec-cms/pull/774 . The idea is that the Record Pages in the CMS that pertain to an AO will have that AO number set as a field, and then using Wagtails REST API, the web app pages can query those pages and display the text. 

So here's my new understanding of what needs to happen:

- [ ] Review and merge in https://github.com/18F/fec-cms/pull/774
- [ ] Someone from FEC manually set AO numbers in production for record articles
- [ ] On AO pages, the web app calls the Wagtail API (`/api/v2/pages/?type=home.RecordPage&advisory_opinion=[AO_NUMBER]&fields=body`)
- [ ] Display the contents of `response.body` on the AO page

Once those are done, we can make a new issue for refining the interaction and adding supporting content.

**Comment by nickykrause** [comment]
Cheryl informed me today that AOs are issued (and immediately published) about one month before the relevant FEC Record articles are written. She noted this as an FYI but also with a question as to how this would fit into the policy group's AO publishing workflow. (e.g., Will they need to remember to go back and update the already-published AO with the record article, when it comes out?)

I'm not saying that Cheryl's point is a problem or anything; I'm just flagging it here as an FYI and so we don't forget that adding this information might have workflow impacts for the FEC.

**Comment by noahmanger** [comment]
FYI @anthonygarvan & @vrajmohan just updated the issue description based on what I understand needs to happen now.
