### ISSUE TITLE
Add plain language summaries to MURs

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2155]
So that a users can quickly understand what an MUR is about, add the approved, plain-language summary that is already published in the FEC Record to each MUR's canonical page.

---

This story is to capture the MUR summaries from Weekly Digest articles, add them to the API response, and then implement them on the front-end. 

~The one unknown here is what the exact rules for this content are and what the best way to get it is. I'm not sure if it exists in a more structured form than what's on the website currently.~

**Update from below:** We only have these from ~2011+. In addition to being in HTML on all the Latest Updates pages, they also have them stored as a separate Word doc, which we can get.

**Sub-tasks**
- [x] Figure out what parts need
- [x] Figure out the best mechanism for getting the content

**Completion criteria:**
- [ ] All available MUR summaries from Weekly Digest articles are associated with their MUR in the database
- [ ] All MURs with new summaries display them on their canonical page
- [ ] On the canonical page, specify that the summary is from the Record and include a link to the Weekly Digest article (which we have on [Latest Updates](https://beta.fec.gov/updates))

**Comment by noahmanger** [comment]
@amykort and @amypike: @patphongs  was just helping me understand what summaries we had available for MURs and AOs. i understand that you wanted the summaries to be drawn from the Record articles, but a couple snags:

1. All Records before ~2011 are PDFs only, which makes them not possible to scrape
2. The Record stopped summarizing MURs around 2009, but the Digest picked up the work when it started
3. The Record has AO summaries in HTML from around 2011 to present, so those are possible

This means that we wouldn’t be able to get summaries for _anything_ prior to 2011, and the only way to get MUR summaries would be to draw them from the Weekly Digest. 

What do you think we should do?

**Comment by AmyKort** [comment]
1. One day, we will start something simple and find out that it is, in fact, simple. 
2. MUR summaries should come from the weekly digests. My understanding is that we have a separate document with all of the MUR summaries, but it is a Word document. Don't know if that's better or worse.
3. I don't know what's best for AOs. Record summaries are more complete, plain language summaries of the case, but we also have shorter summaries in the weekly digests.

**Comment by noahmanger** [comment]
1. One day  :)
2. Word document would be amazing actually. Having them all in one place is significantly better than needing to parse individual pages. Would @ChristianHilland have this doc by chance?
3. Is there a similar consolidated document for AO summaries from the Digests?

**Comment by AmyKort** [comment]
Yes! @ChristianHilland is our best bet for the MUR and AO summary information.

**Comment by AmyKort** [comment]
Alternatively, for AOs, we could ask Info for help pulling out the summaries. AOs are a smaller universe of documents. @amypike

**Comment by amypike** [comment]
@noah, I'm sorry,  our resources are so difficult to work with! I agree with @amykort that  Lifting MUR summaries from the Digest sounds like the way to go, but the Digest summaries of AOs are not as robust as those in the Record.  I agree with our Commissioners that we really should leverage the information in the Record and I will even volunteer to lift the summaries from any internal sources we have.  The universe of AOs isn't scary large and the summaries are short. I can speak to Greg next week and find out what resources Info has.

**Comment by noahmanger** [comment]
Ok, awesome. Yeah if someone there could help with the legwork of grabbing those descriptions then that makes this a lot easier. Let me know when you're ready to do that and we can work together to figure out the best way to store it.

**Comment by AmyKort** [comment]
My (new) understanding is that we have plain language summaries for all MURs but these summaries are not consolidated in one place, but rather in a number of Word documents. It'll take a fair amount of effort to pull them together. I still think this is worth prioritizing because we don't otherwise have quick descriptions of MURs to help users. But, given the extra work involved, we'll need to decide how it stacks up against our other really important priorities.

**Comment by noahmanger** [comment]
Ok, that sounds good. We'll discuss Tuesday if we want to do this this sprint.
