### ISSUE TITLE
GovCloud release checklist

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2270]
The next release is going to be complicated with the GovCloud migration. Here's a checklist @LindsayYoung put together, which we should keep updated as we go:

# Communication and logistics
 - [ ] Reach out to content creators to create cloud.gov accounts 
 - [ ] Reach out to FEC and 18f teammates with the new dev and stage urls

# Prep for deploy
 - [x] Content freeze on cms
 - [x] Make final cms snapshot
 - [x] Upload cms snapshot to prod, stage and dev (if we are short on time we can worry about stage and dev later, but I would like to get them out of the way)

# Deploy apps and QA
 - [x] Deploy cms
 - [x] Deploy web app
 - [x] Deploy eregs
 - [x] Load legal data on to prod
 - [x] Deploy api
 - [ ] Test API by temporary removing white listing and test it
 - [x] Point the web app directly to the API and compare various committees, candidates and views.
 
# After QA
 - [ ] Re-configure API URL for web app and re-enable API white listing 
 - [ ] Deploy the proxy
 - [ ] Stop the proxy on EW (we may have to take the old proxy down first, but we'll see, it doesn't take long to deploy if that is the way we have to do it)
