### ISSUE TITLE
Design new charts for candidate and committee pages

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#232]
**Goal:** Honestly and usefully represent the totals data over time in a visual way.

**Criteria:** Static mockups of charts for candidate and committee pages.

**Tasks:**
- [x] Sketch options with Shawn
- [x] Discuss options with @LindsayYoung 
- [x] Mockup charts in Sketch

**Comment by noahmanger** [comment]
Ok, here's some new charts for the candidate page:

![candidate - 1](https://cloud.githubusercontent.com/assets/1696495/5731476/a88478f0-9b38-11e4-9e6c-af99321a7270.png)

And for the committee page. The idea with this one is that either clicking the "Toggle analysis" buttons or clicking on the "individual contributions" bars the chart/table will transform into the second view, showing the breakdown. Eventually we can show this type of breakdown for all types of contributions once we have the itemized info. For now it can just be for Itemized Individual Contributions.

![committees - 1a](https://cloud.githubusercontent.com/assets/1696495/5731639/c2d3cd44-9b3a-11e4-80cc-eca7b2037dcb.png)
![committees - 1b](https://cloud.githubusercontent.com/assets/1696495/5731640/c2d5b8a2-9b3a-11e4-9415-fb34b08b4502.png)

**Comment by LindsayYoung** [comment]
All my thoughts:

Candidate Page - 

- For me, the horizontal alignment of the basic information is harder to scan for me than the previous layout.

- I would prefer we list elections by election cycle. In the future, it would be  great to explore views that highlight the primary or general election. If we are just looking at itemized spending, we can tease the information by general and primary, we should also be able to tell who doesn't make it past the primary. So, we have some data to work with but creating general vs primary pages is hard and I don't want to commit to that yet.  Additionally, once the primary is done, people are still reporting on how much the candidate raised in the course of the election, not just the general. I think the overall election should be our first priority. 

- For the Financial Summary description, maybe we should switch out "full picture" with "overview"

- I really like what you chose for the quick links

- For the mouse over, I think we should also have the dollar amount.

Committee Page -

- I am going to hire Sam Moneys too!

- Just a thought, will the toggling of charts be harder to implement for 508 reasons or for people without javascript? You know better than I do.

Overall -

- This is looking great, I think the look is getting cleaner and clearer as we go along. I really like it.

Thanks @noahmanger!

**Comment by noahmanger** [comment]
Thanks, @LindsayYoung . Good points. I want to keep the new layout of the basic info for now because a) it groups the types of info more logically (disbursements & receipts vs cash) and it also mirrors the way this table is layed out on the committee page. I imagine it will change in the future, but I want to see how this works for now.

**Comment by noahmanger** [comment]
Oh, and re: the chart toggling — it shouldn't be a problem for accessibility, but you're right, we'll need a non-js solution. The best way to go there might just be to display both by default.

**Comment by noahmanger** [comment]
Posted in Drive. So closing this out.
