### ISSUE TITLE
Election data fixes

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2590]
Here's a fresh issue with the things that need to be fixed with elections dates and data (consolidating https://github.com/18F/openFEC/issues/2544 , https://github.com/18F/openFEC-web-app/issues/2227, https://github.com/18F/openFEC/issues/2428:

- [x] Duplicative results when filtering for GA: https://fec-dev-api.app.cloud.gov/v1/elections/search/?api_key=&cycle=2018&state=GA
- [x] States without senate elections in 2018 (e.g. Oregon, Colorado) show up as having a senate election. This is not a problem on production.
- [x] The [Alabama special senate election](https://www.fec.gov/data/elections/senate/AL/2018/) displays the incorrect candidates (https://github.com/18F/openFEC-web-app/issues/2227)
- [ ] [Texas house candidates for 2018](https://www.fec.gov/data/candidates/house/?cycle=2018&state=TX&district=07) include two who are 2016 candidates (Espinoza and Lloyd) (https://github.com/18F/openFEC/issues/2428)
- [x] Incorrect candidates showing up on [Colorado 6th page](https://www.fec.gov/data/elections/house/CO/06/2018/) (https://github.com/18F/FEC/issues/4387)
- [x] Duplicate Alaska listing https://github.com/18F/openFEC-web-app/issues/2245
- [x] Election search results for state does not show all districts https://github.com/18F/openFEC-web-app/issues/2256

**Comment by jontours** [comment]
Recording this before I forget; the issue with the Texas candidates has nothing to do with the election endpoints.  I'll try to get it knocked it out with the PR but it may be a straggler.

**Comment by jontours** [comment]
Colorado issue is fixed with latest PR.  I verified my work with open source information about that election (which was probably sourced from the FEC).  I'm showing 5 candidates for 2018 CO 6th.  
4 Democrats and 1 Republican (the incumbent).

**Comment by jontours** [comment]
And finally the issue with Texas candidates done now as well, turns out it was related to some of the other problems (but was on a unique endpoint).

**Comment by jontours** [comment]
After looking at the code, think the issue with Texas may not have been a problem after all, I think the front-end just needs to pass in `election_full` = true.  I'm not sure though, maybe have to talk about that one @noahmanger @LindsayYoung.

**Comment by LindsayYoung** [comment]
Moving the TX case to its own issue
