### ISSUE TITLE
Migrate WIP items to DB migrations

### ISSUE THREAD

**Issue by ccostino** [18F/openFEC#2797]
With the DB migrations work complete as of PR #2768, there is some work currently in progress that we need to port over immediately to ensure it can continue on.  This includes:

* [x] Audit search (PR #2700)
* [x] FECP aggregate and fitem_sched tables (PR #2792)
* [x] Reverting the calendar (PR #2783)

If there are any others, please add them to this list so we can keep track of them all and get them ported over!

/cc @fec-jli, @fecjjeng, @pkfec, since your work is captured here already

**Comment by fecjjeng** [comment]
@ccostino I saw you created this issue #2797 to track the WIP items to DB migrations including the aggregate tables and partitioned tables. I had created a sql file that includes the aggregate tables (V42_disclosure_aggregate_tables.sql), should I check it in?  Or you are tracking it already?  I may not be able to complete the sql file for the partitioned tables before my leave on Wednesday but can continue after I come back if that is not urgent.

**Comment by ccostino** [comment]
Hi @fecjjeng - no I'm not tracking any of the work itself as that is on everyone else's machines, I have no access to it unless it's pushed remotely. :-)

That said, yes, if you have work to create new migrations then please update your PR (commit the files locally and push your branch again)!  Once you're back, we can coordinate with @LindsayYoung to help finish things up. :-)

**Comment by ccostino** [comment]
@fecjjeng, @hcaofec, @vrajmohan, and I all caught up about the `fec_fitem` aggregate and partition tables, and we're actually already good to go as those tables were all rolled up in the baseline migrations. :-)

Due to this, we're closing PR #2792 and marking it off as complete!

**Comment by ccostino** [comment]
@LindsayYoung and I worked on getting PR #2783 in shape and are very close!  Just a little more work to do and that should be in good shape. :-)

**Comment by ccostino** [comment]
We finished work with PR #2783 and merged it in!  Just audit search left. :-)

**Comment by ccostino** [comment]
Audit search is now down as well with PR #2700!  However, we are waiting for the release to go out before merging to `develop` to keep migrations in sync.
